# Generated by Django 5.0.4 on 2024-04-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='codigo_isbn',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='codigo_isbn_libro'),
        ),
    ]
