# Generated by Django 5.0.4 on 2024-04-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_libro_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriausuario',
            old_name='tipoUsuario',
            new_name='id_tipo_usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='tipoUsuario',
            new_name='id_tipo_usuario',
        ),
        migrations.AddField(
            model_name='categoriausuario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
