# Generated by Django 4.2.11 on 2024-04-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_libro_codigo_isbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='cantidad_libros',
            fields=[
                ('id_cantidad', models.AutoField(primary_key=True, serialize=False, verbose_name='Id cantidad libros')),
                ('nombre_libro', models.CharField(max_length=30, verbose_name='nombre_libro')),
                ('cantidad', models.IntegerField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
