# Generated by Django 5.0.4 on 2024-04-26 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_rename_tipousuario_categoriausuario_id_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='email',
            new_name='useremail',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='nombreApellido',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
    ]
