# Generated by Django 5.0.4 on 2024-04-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_rename_contraseña_usuario_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriausuario',
            name='id_tipo_usuario',
            field=models.IntegerField(unique=True),
        ),
    ]
